let asset = {"assets": {
    "ProjectSetupScenario_realAsset1": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 200,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 200,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "1",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "ProjectSetupScenario_realAsset2": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 400,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 400,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "2",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "ProjectSetupScenario_realAsset3": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 600,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 600,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "3",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "ProjectSetupScenario_realAsset4": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 800,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 800,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "4",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "OutcomeScenario_realAsset5": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 1000,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 1000,
        "y": 100
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "5",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "OutcomeScenario_realAsset6": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 1200,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 1200,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "6",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "OutcomeScenario_realAsset7": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 1400,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 1400,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "7",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "OutcomeScenario_realAsset8": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 200,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 200,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "8",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "AttachConfig_realAsset9": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 400,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 400,
        "y": 250
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "9",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 0"
    },
    "realAsset10": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 200,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 200,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "10",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset11": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 300,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 300,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "11",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "OutcomeScenario_realAsset12": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 400,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 400,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "12",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "OutcomeScenario_realAsset13": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 500,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 500,
        "y": 100
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "13",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset14": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 600,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 600,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "14",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset15": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 700,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 700,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "15",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset16": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 800,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 800,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "16",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset17": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 900,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 900,
        "y": 100
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "17",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset18": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 1000,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 1000,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "18",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset19": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 1100,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 1100,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "19",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset20": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 1200,
        "y": 100
      },
      "mapIdCoordinates": {
        "x": 1200,
        "y": 100
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "monoA3Monthly": 1000,
      "colorA3Monthly": 3000,
      "colorA4Monthly": 700,
      "monoA4Monthly": 300,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "20",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "OutcomeApiTests_realAsset21": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 100,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 100,
        "y": 250
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "21",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "Opti_Report_Asset22": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 200,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 200,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "22",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "Opti_Report_Asset23": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 300,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 300,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "23",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "Opti_Report_Asset24": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 400,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 400,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "24",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset25": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 500,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 500,
        "y": 250
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "25",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset26": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 600,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 600,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "26",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset27": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 700,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 700,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "27",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset28": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 800,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 800,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "28",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset29": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 900,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 900,
        "y": 250
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "29",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset30": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 1000,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 1000,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "30",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset31": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 1100,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 1100,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "31",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset32": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 1200,
        "y": 250
      },
      "mapIdCoordinates": {
        "x": 1200,
        "y": 250
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "32",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset33": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 100,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 100,
        "y": 400
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "33",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset34": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 200,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 200,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "34",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset35": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 300,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 300,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "35",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset36": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 400,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 400,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "36",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset37": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 500,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 500,
        "y": 400
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "37",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset38": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 600,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 600,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "38",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset39": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 700,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 700,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "39",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset40": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 800,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 800,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "40",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset41": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 900,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 900,
        "y": 400
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "41",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset42": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 1000,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 1000,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "42",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset43": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 1100,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 1100,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "43",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset44": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 1200,
        "y": 400
      },
      "mapIdCoordinates": {
        "x": 1200,
        "y": 400
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "44",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "AssetLookup_realAsset45": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 100,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 100,
        "y": 550
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "45",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset46": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 200,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 200,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "46",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset47": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 300,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 300,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "47",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset48": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 400,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 400,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "48",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset49": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 500,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 500,
        "y": 550
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "49",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset50": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 600,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 600,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "50",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset51": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 700,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 700,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "51",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset52": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 800,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 800,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "52",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset53": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 900,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 900,
        "y": 550
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "53",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset54": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 1000,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 1000,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "54",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset55": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 1100,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 1100,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "55",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset56": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 1200,
        "y": 550
      },
      "mapIdCoordinates": {
        "x": 1200,
        "y": 550
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "56",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset57": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 100,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 100,
        "y": 700
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "57",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset58": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 200,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 200,
        "y": 700
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "58",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset59": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 300,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 300,
        "y": 700
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "59",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset60": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 400,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 400,
        "y": 700
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "60",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "OutcomeApiTests_realAsset61": {
      "originalId": "5af290285bdaabb1212e70f1",
      "inventory": true,
      "plotted": true,
      "labelCoordinates": {
        "x": 500,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 500,
        "y": 700
      },
      "state": "real",
      "pricingSource": "project",
      "deviceType": "printColor",
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "61",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "realAsset62": {
      "originalId": "5af290285bdaabb1212e70f2",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printColor",
      "labelCoordinates": {
        "x": 600,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 600,
        "y": 700
      },
      "make": "HP",
      "model": "LaserJet Pro 400 Color M451dn Printer",
      "serialNumber": "CNDF262790",
      "iPAddress": "192.168.1.14",
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957A",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "62",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "RemoveAsset_realAsset63": {
      "originalId": "5af290285bdaabb1212e70f3",
      "inventory": true,
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "printMono",
      "labelCoordinates": {
        "x": 700,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 700,
        "y": 700
      },
      "make": "HP",
      "model": "LaserJet 9040 Printer",
      "serialNumber": "A1A0101011",
      "iPAddress": "192.168.1.1",
      "state": "real",
      "colorTotalMonthly": 1200,
      "monoTotalMonthly": 750,
      "proposedMonthlyPageVolumeColor": 1200,
      "proposedMonthlyPageVolumeMono": 750,
      "productId": "12343",
      "productNumber": "Q7697A",
      "hasDuplex": false,
      "country": "UNITED STATES",
      "assetPropertiesHash": "US+Shared Devices+CE957A+IB+",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "63",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    },
    "RemoveAsset_realAsset64": {
      "originalId": "5af290285bdaabb1212e70f4",
      "plotted": true,
      "pricingSource": "project",
      "deviceType": "plotter",
      "labelCoordinates": {
        "x": 800,
        "y": 700
      },
      "mapIdCoordinates": {
        "x": 800,
        "y": 700
      },
      "make": "HP",
      "model": "LaserJet Pro 450 Color Printer",
      "serialNumber": "CNDF262791",
      "iPAddress": "192.168.1.15",
      "inventory": true,
      "state": "real",
      "colorTotalMonthly": 3700,
      "monoTotalMonthly": 1300,
      "proposedMonthlyPageVolumeColor": 3700,
      "proposedMonthlyPageVolumeMono": 1300,
      "productId": "999999",
      "productNumber": "CE957B",
      "hasDuplex": true,
      "assetPropertiesHash": "US+Shared Devices+CE957B+IB+",
      "country": "UNITED STATES",
      "region": "AMS",
      "countryCode": "US",
      "assetAccessories": [],
      "noOfSites": null,
      "totalEmployees": null,
      "assetNumber": "64",
      "sku": null,
      "defaultBreakFix": null,
      "defaultBillingModel": null,
      "maintenanceKit": null,
      "floor": "Floor 1"
    }
  }};
console.log(asset.assets.realAsset41);
