function objectMerge() {    let out = {};
  for (let i = 0; i < arguments.length; i++) {
    for (let key in arguments[i]) {
      out[key] = arguments[i][key];
    }
  }
  return out;
}

var obj1 = {
      "level": {
        "name": "level",
        "field": "level",
        "width": 250,
        "pinnedLeft": true,
        "enableColumnMoving": false,
        "enableHiding": false,
        "enableSorting": false,
        "enableColumnMenu": false,
        "enableFiltering": false,
        "headerCellClass": "levelColumn"
      },
      "selection": {
        "name": "selection",
        "field": "selection",
        "width": 30,
        "enableFiltering": false,
        "enableHiding": false,
        "enableSorting": false,
        "enableColumnMenu": false,
        "pinnedLeft": true,
        "enableColumnMoving": false,
        "headerCellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/headerTemplate.html",
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/cellTemplate.html",
        "headerCellClass": "selectionColumn"
      },
      "subEnvID": {
        "name": "subEnvID",
        "field": "subEnvID",
        "width": 120,
        "enablePinning": false,
        "headerCellClass": "subEnvIDColumn",
        "type": "number",
        "minWidth": 120
      },
      "assetAbbreviation": {
        "name": "assetAbbreviation",
        "field": "assetAbbreviation",
        "width": 120,
        "enablePinning": false,
        "headerCellClass": "assetAbbreviationColumn",
        "type": "string",
        "minWidth": 120
      },
      "mapId": {
        "name": "mapId",
        "field": "mapId",
        "width": 120,
        "enablePinning": false,
        "headerCellClass": "mapIdColumn",
        "type": "number",
        "minWidth": 120,
        "cellTooltip": true
      },
      "deviceModel": {
        "name": "deviceModel",
        "field": "deviceModel",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "deviceModelColumn",
        "minWidth": 120
      },
      "serialNumber": {
        "name": "serialNumber",
        "field": "serialNumber",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "serialNumberColumn",
        "minWidth": 120
      },
      "pageSize": {
        "name": "pageSize",
        "field": "pageSize",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "pageSizeColumn",
        "minWidth": 120
      },
      "deviceType": {
        "name": "deviceType",
        "field": "deviceType",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "deviceTypeColumn",
        "minWidth": 120
      },
      "deviceQty": {
        "name": "deviceQty",
        "field": "deviceQty",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/deviceQtyCell.html",
        "headerCellClass": "deviceQtyColumn",
        "type": "number",
        "minWidth": 120
      },
      "hwDisposition": {
        "name": "hwDisposition",
        "field": "hwDisposition",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/hwDispositionCell.html",
        "headerCellClass": "hwDispositionColumn",
        "minWidth": 120
      },
      "zone": {
        "name": "zone",
        "field": "zone",
        "width": 120,
        "enablePinning": false,
        "headerCellClass": "zoneColumn",
        "type": "number",
        "minWidth": 120
      },
      "sku": {
        "name": "sku",
        "field": "sku",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "skuColumn",
        "minWidth": 120
      },
      "floor": {
        "name": "floor",
        "field": "floor",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "headerCellClass": "floorColumn",
        "minWidth": 120
      },
      "department": {
        "name": "department",
        "field": "department",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "headerCellClass": "deptColumn",
        "minWidth": 120
      },
      "pvtInA3": {
        "name": "pvtInA3",
        "field": "pvtInA3",
        "width": 120,
        "cellTooltip": false,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/pvtInA3Cell.html",
        "headerCellClass": "pvtInA3Column",
        "minWidth": 120
      },
      "pvtIn": {
        "name": "pvtIn",
        "field": "pvtIn",
        "width": 120,
        "cellTooltip": false,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/pvtInCell.html",
        "headerCellClass": "pvtInColumn",
        "minWidth": 120
      },
      "pvtOutA3": {
        "name": "pvtOutA3",
        "field": "pvtOutA3",
        "width": 120,
        "cellTooltip": false,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/pvtOutA3Cell.html",
        "headerCellClass": "pvtOutA3Column",
        "minWidth": 120
      },
      "pvtOut": {
        "name": "pvtOut",
        "field": "pvtOut",
        "width": 120,
        "cellTooltip": false,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/pvtOutCell.html",
        "headerCellClass": "pvtOutColumn",
        "minWidth": 120
      },
      "monoPages": {
        "name": "monoPages",
        "field": "monoPages",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/monoPageCountCell.html",
        "headerCellClass": "monoPagesColumn",
        "minWidth": 120
      },
      "colorPages": {
        "name": "colorPages",
        "field": "colorPages",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/colorPageCountCell.html",
        "headerCellClass": "colorPagesColumn",
        "minWidth": 120
      },
      "colorPro": {
        "name": "colorPro",
        "field": "colorPro",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorPro",
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/colorProPageCountCell.html",
        "minWidth": 120
      },
      "ampv": {
        "name": "ampv",
        "field": "ampv",
        "width": 120,
        "enablePinning": false,
        "cellTooltip": true,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/totalPagesCountCell.html",
        "headerCellClass": "ampvColumn",
        "minWidth": 120
      },
      "monthlyMonoPages": {
        "name": "monthlyMonoPages",
        "field": "monthlyMonoPages",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/monthlyMonoPagesCountCell.html",
        "headerCellClass": "monthlyMonoPagesColumn",
        "minWidth": 120
      },
      "monthlyColorPages": {
        "name": "monthlyColorPages",
        "field": "monthlyColorPages",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/monthlyColorPagesCountCell.html",
        "headerCellClass": "monthlyColorPagesColumn",
        "minWidth": 120
      },
      "monthlyColorProfPages": {
        "name": "monthlyColorProfPages",
        "field": "monthlyColorProfPages",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/monthlyColorProfPagesCountCell.html",
        "headerCellClass": "monthlyColorProfPagesColumn",
        "minWidth": 120
      },
      "monthlyPages": {
        "name": "monthlyPages",
        "field": "monthlyPages",
        "width": 120,
        "enablePinning": false,
        "cellTooltip": true,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/monthlyPagesCountCell.html",
        "headerCellClass": "monthlyPagesColumn",
        "minWidth": 120
      },
      "colorTotalPagesPercentage": {
        "name": "colorTotalPagesPercentage",
        "field": "colorTotalPagesPercentage",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/colorTotalPagesPercentageCountCell.html",
        "headerCellClass": "colorTotalPagesPercentageColumn",
        "minWidth": 120
      },
      "colorProTotalPagesPercentage": {
        "name": "colorProTotalPagesPercentage",
        "field": "colorProTotalPagesPercentage",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "headerCellClass": "colorProTotalPagesPercentageColumn",
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/colorProTotalPagesPercentageCountCell.html",
        "minWidth": 120
      },
      "a3Percentage": {
        "name": "a3Percentage",
        "field": "a3Percentage",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "a3Percentage",
        "minWidth": 120
      },
      "colorA3Percentage": {
        "name": "colorA3Percentage",
        "field": "colorA3Percentage",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorA3Percentage",
        "minWidth": 120
      },
      "monoA3Percentage": {
        "name": "monoA3Percentage",
        "field": "monoA3Percentage",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoA3Percentage",
        "minWidth": 120
      },
      "age": {
        "name": "age",
        "field": "age",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "age",
        "minWidth": 120
      },
      "lifeTimeEngineLife": {
        "name": "lifeTimeEngineLife",
        "field": "lifeTimeEngineLife",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "lifeTimeEngineLife",
        "minWidth": 120
      },
      "eoslPast": {
        "name": "eoslPast",
        "field": "eoslPast",
        "width": 120,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "eoslPast",
        "minWidth": 120
      },
      "comments": {
        "name": "comments",
        "field": "comments",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "commentsColumn",
        "minWidth": 120
      },
      "netPriceUsd": {
        "name": "netPriceUsd",
        "field": "netPriceUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "netPriceUsdColumn",
        "minWidth": 120
      },
      "upfrontChargeUsd": {
        "name": "upfrontChargeUsd",
        "field": "upfrontChargeUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "upfrontChargeUsdColumn",
        "minWidth": 120
      },
      "totalRevenueUsd": {
        "name": "totalRevenueUsd",
        "field": "totalRevenueUsd",
        "width": 120,
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalRevenueUsdColumn",
        "minWidth": 120
      },
      "totalCPPUsd": {
        "name": "totalCPPUsd",
        "field": "totalCPPUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPUsdColumn",
        "minWidth": 120
      },
      "monoCPPUsd": {
        "name": "monoCPPUsd",
        "field": "monoCPPUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoCPPUsdColumn",
        "minWidth": 120
      },
      "colorCPPUsd": {
        "name": "colorCPPUsd",
        "field": "colorCPPUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorCPPUsdColumn",
        "minWidth": 120
      },
      "baseFeeUsd": {
        "name": "baseFeeUsd",
        "field": "baseFeeUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "baseFeeUsdColumn",
        "minWidth": 120
      },
      "monoClickUsd": {
        "name": "monoClickUsd",
        "field": "monoClickUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoClickUsdColumn",
        "minWidth": 120
      },
      "colorClickUsd": {
        "name": "colorClickUsd",
        "field": "colorClickUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "colorClickUsdColumn"
      },
      "bestColorClickUsd": {
        "name": "bestColorClickUsd",
        "field": "bestColorClickUsd",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "bestColorClickUsdColumn"
      },
      "netPriceLc": {
        "name": "netPriceLc",
        "field": "netPriceLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "netPriceLcColumn"
      },
      "upfrontChargeLc": {
        "name": "upfrontChargeLc",
        "field": "upfrontChargeLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "upfrontChargeLcColumn"
      },
      "totalRevenueLc": {
        "name": "totalRevenueLc",
        "field": "totalRevenueLc",
        "width": 120,
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "totalRevenueLcColumn"
      },
      "totalCPPLc": {
        "name": "totalCPPLc",
        "field": "totalCPPLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "totalCPPLcColumn"
      },
      "monoCPPLc": {
        "name": "monoCPPLc",
        "field": "monoCPPLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "monoCPPLcColumn"
      },
      "colorCPPLc": {
        "name": "colorCPPLc",
        "field": "colorCPPLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "colorCPPLcColumn"
      },
      "baseFeeLc": {
        "name": "baseFeeLc",
        "field": "baseFeeLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "baseFeeLcColumn"
      },
      "monoClickLc": {
        "name": "monoClickLc",
        "field": "monoClickLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "monoClickLcColumn"
      },
      "colorClickLc": {
        "name": "colorClickLc",
        "field": "colorClickLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "minWidth": 120,
        "headerCellClass": "colorClickLcColumn"
      },
      "bestColorClickLc": {
        "name": "bestColorClickLc",
        "field": "bestColorClickLc",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "bestColorClickLcColumn",
        "minWidth": 120
      },
      "monoCppToner": {
        "name": "monoCppToner",
        "field": "monoCppToner",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoCppTonerColumn",
        "minWidth": 120,
        "group": "tonerColumns"
      },
      "colorCppToner": {
        "name": "colorCppToner",
        "field": "colorCppToner",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorCppTonerColumn",
        "minWidth": 120,
        "group": "tonerColumns"
      },
      "totalCppToner": {
        "name": "totalCppToner",
        "field": "totalCppToner",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCppTonerColumn",
        "minWidth": 120,
        "group": "tonerColumns"
      },
      "monoTcoToner": {
        "name": "monoTcoToner",
        "field": "monoTcoToner",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoTcoTonerColumn",
        "minWidth": 120,
        "group": "tonerColumns"
      },
      "colorTcoToner": {
        "name": "colorTcoToner",
        "field": "colorTcoToner",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorTcoTonerColumn",
        "minWidth": 120,
        "group": "tonerColumns"
      },
      "totalTcoToner": {
        "name": "totalTcoToner",
        "field": "totalTcoToner",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalTcoTonerColumn",
        "minWidth": 120,
        "group": "tonerColumns"
      },
      "detailsToner": {
        "name": "detailsToner",
        "field": "detailsToner",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/tonerDetailsTemplate.html",
        "headerCellClass": "detailsTonerColumn",
        "minWidth": 120,
        "group": "tonerColumns"
      },
      "laborRateRP": {
        "name": "laborRateRP",
        "field": "laborRateRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "laborRateRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "laborTravelHoursRP": {
        "name": "laborTravelHoursRP",
        "field": "laborTravelHoursRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "laborTravelHoursRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "laborRepairHoursRP": {
        "name": "laborRepairHoursRP",
        "field": "laborRepairHoursRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "laborRepairHoursRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "monoCppRP": {
        "name": "monoCppRP",
        "field": "monoCppRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoCppRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "colorCppRP": {
        "name": "colorCppRP",
        "field": "colorCppRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorCppRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "totalCppRP": {
        "name": "totalCppRP",
        "field": "totalCppRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCppRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "monoTcoRP": {
        "name": "monoTcoRP",
        "field": "monoTcoRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoTcoRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "colorTcoRP": {
        "name": "colorTcoRP",
        "field": "colorTcoRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorTcoRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "totalTcoRP": {
        "name": "totalTcoRP",
        "field": "totalTcoRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalTcoRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "detailsRP": {
        "name": "detailsRP",
        "field": "detailsRP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/replaceablePartsDetailsTemplate.html",
        "headerCellClass": "detailsRPColumn",
        "minWidth": 120,
        "group": "rpColumns"
      },
      "avgPwcService": {
        "name": "avgPwcService",
        "field": "avgPwcService",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "avgPwcServiceColumn",
        "minWidth": 120,
        "group": "serviceColumns"
      },
      "monoCppService": {
        "name": "monoCppService",
        "field": "monoCppService",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoCppServiceColumn",
        "minWidth": 120,
        "group": "serviceColumns"
      },
      "colorCppService": {
        "name": "colorCppService",
        "field": "colorCppService",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorCppServiceColumn",
        "minWidth": 120,
        "group": "serviceColumns"
      },
      "totalCppService": {
        "name": "totalCppService",
        "field": "totalCppService",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCppServiceColumn",
        "minWidth": 120,
        "group": "serviceColumns"
      },
      "monoTcoService": {
        "name": "monoTcoService",
        "field": "monoTcoService",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoTcoServiceColumn",
        "minWidth": 120,
        "group": "serviceColumns"
      },
      "colorTcoService": {
        "name": "colorTcoService",
        "field": "colorTcoService",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorTcoServiceColumn",
        "minWidth": 120,
        "group": "serviceColumns"
      },
      "totalTcoService": {
        "name": "totalTcoService",
        "field": "totalTcoService",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalTcoServiceColumn",
        "minWidth": 120,
        "group": "serviceColumns"
      },
      "avgPowPricePower": {
        "name": "avgPowPricePower",
        "field": "avgPowPricePower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "avgPowPricePowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "workHoursPerDayPower": {
        "name": "workHoursPerDayPower",
        "field": "workHoursPerDayPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "workHoursPerDayPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "workDaysPerWeekPower": {
        "name": "workDaysPerWeekPower",
        "field": "workDaysPerWeekPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "workDaysPerWeekPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "weeksPerYearPower": {
        "name": "weeksPerYearPower",
        "field": "weeksPerYearPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "weeksPerYearPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "isOnNightAndWeekends": {
        "name": "isOnNightAndWeekends",
        "field": "isOnNightAndWeekends",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "isOnNightAndWeekendsColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "powerRateActive": {
        "name": "powerRateActive",
        "field": "powerRateActive",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "powerRateActiveColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "powerRateIdle": {
        "name": "powerRateIdle",
        "field": "powerRateIdle",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "powerRateIdleColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "powerRateSave": {
        "name": "powerRateSave",
        "field": "powerRateSave",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "powerRateSaveColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "monoCppPower": {
        "name": "monoCppPower",
        "field": "monoCppPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoCppPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "colorCppPower": {
        "name": "colorCppPower",
        "field": "colorCppPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorCppPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "totalCppPower": {
        "name": "totalCppPower",
        "field": "totalCppPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCppPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "monoTcoPower": {
        "name": "monoTcoPower",
        "field": "monoTcoPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoTcoPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "colorTcoPower": {
        "name": "colorTcoPower",
        "field": "colorTcoPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorTcoPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "totalTcoPower": {
        "name": "totalTcoPower",
        "field": "totalTcoPower",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalTcoPowerColumn",
        "minWidth": 120,
        "group": "powerColumns"
      },
      "paperCostPerSheetPaper": {
        "name": "paperCostPerSheetPaper",
        "field": "paperCostPerSheetPaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "paperCostPerSheetPaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "duplexPercentagePaper": {
        "name": "duplexPercentagePaper",
        "field": "duplexPercentagePaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "duplexPercentagePaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "isDuplexCapablePaper": {
        "name": "isDuplexCapablePaper",
        "field": "isDuplexCapablePaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "isDuplexCapablePaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "monoCppPaper": {
        "name": "monoCppPaper",
        "field": "monoCppPaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoCppPaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "colorCppPaper": {
        "name": "colorCppPaper",
        "field": "colorCppPaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorCppPaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "totalCppPaper": {
        "name": "totalCppPaper",
        "field": "totalCppPaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCppPaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "monoTcoPaper": {
        "name": "monoTcoPaper",
        "field": "monoTcoPaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoTcoPaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "colorTcoPaper": {
        "name": "colorTcoPaper",
        "field": "colorTcoPaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorTcoPaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "totalTcoPaper": {
        "name": "totalTcoPaper",
        "field": "totalTcoPaper",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalTcoPaperColumn",
        "minWidth": 120,
        "group": "paperColumns"
      },
      "deviceCostHardware": {
        "name": "deviceCostHardware",
        "field": "deviceCostHardware",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "deviceCostHardwareColumn",
        "minWidth": 120,
        "group": "hardwareColumns"
      },
      "monoCppHardware": {
        "name": "monoCppHardware",
        "field": "monoCppHardware",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoCppHardwareColumn",
        "minWidth": 120,
        "group": "hardwareColumns"
      },
      "colorCppHardware": {
        "name": "colorCppHardware",
        "field": "colorCppHardware",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorCppHardwareColumn",
        "minWidth": 120,
        "group": "hardwareColumns"
      },
      "totalCppHardware": {
        "name": "totalCppHardware",
        "field": "totalCppHardware",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCppHardwareColumn",
        "minWidth": 120,
        "group": "hardwareColumns"
      },
      "monoTcoHardware": {
        "name": "monoTcoHardware",
        "field": "monoTcoHardware",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "monoTcoHardwareColumn",
        "minWidth": 120,
        "group": "hardwareColumns"
      },
      "colorTcoHardware": {
        "name": "colorTcoHardware",
        "field": "colorTcoHardware",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "colorTcoHardwareColumn",
        "minWidth": 120,
        "group": "hardwareColumns"
      },
      "totalTcoHardware": {
        "name": "totalTcoHardware",
        "field": "totalTcoHardware",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalTcoHardwareColumn",
        "minWidth": 120,
        "group": "hardwareColumns"
      },
      "totalEnergyInKWH": {
        "name": "totalEnergyInKWH",
        "field": "totalEnergyInKWH",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalEnergyInKWHColumn",
        "minWidth": 120,
        "group": "carbonColumns"
      },
      "co2PaperKG": {
        "name": "co2PaperKG",
        "field": "co2PaperKG",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "co2PaperKGColumn",
        "minWidth": 120,
        "group": "carbonColumns"
      },
      "energyCO2KG": {
        "name": "energyCO2KG",
        "field": "energyCO2KG",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "energyCO2KGColumn",
        "minWidth": 120,
        "group": "carbonColumns"
      },
      "energyCO2KGbyGeography": {
        "name": "energyCO2KGbyGeography",
        "field": "energyCO2KGbyGeography",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "energyCO2KGbyGeographyColumn",
        "minWidth": 120,
        "group": "carbonColumns"
      },
      "noOfTreesCutDown": {
        "name": "noOfTreesCutDown",
        "field": "noOfTreesCutDown",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "noOfTreesCutDownColumn",
        "minWidth": 120,
        "group": "carbonColumns"
      },
      "literOfOilRequired": {
        "name": "literOfOilRequired",
        "field": "literOfOilRequired",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "literOfOilRequiredColumn",
        "minWidth": 120,
        "group": "carbonColumns"
      },
      "totalAssetManagementCost": {
        "name": "totalAssetManagementCost",
        "field": "totalAssetManagementCost",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "indirectCosts"
      },
      "supplyProcessTotalManHrsCostsPerYr": {
        "name": "supplyProcessTotalManHrsCostsPerYr",
        "field": "supplyProcessTotalManHrsCostsPerYr",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "indirectCosts"
      },
      "totalDeviceSpaceCostperYr": {
        "name": "totalDeviceSpaceCostperYr",
        "field": "totalDeviceSpaceCostperYr",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "indirectCosts"
      },
      "totalPurchasingCostofDeviceperYr": {
        "name": "totalPurchasingCostofDeviceperYr",
        "field": "totalPurchasingCostofDeviceperYr",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "indirectCosts"
      },
      "helpDeskCostperPrinterBasedonNumberofPrinters": {
        "name": "helpDeskCostperPrinterBasedonNumberofPrinters",
        "field": "helpDeskCostperPrinterBasedonNumberofPrinters",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "indirectCosts"
      },
      "helpDeskCostperPrinterBasedonNumberofUsers": {
        "name": "helpDeskCostperPrinterBasedonNumberofUsers",
        "field": "helpDeskCostperPrinterBasedonNumberofUsers",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "indirectCosts"
      },
      "totalITMgmtCostofDevicePerYr": {
        "name": "totalITMgmtCostofDevicePerYr",
        "field": "totalITMgmtCostofDevicePerYr",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "indirectCosts"
      },
      "totalMonoCPP": {
        "name": "totalMonoCPP",
        "field": "totalMonoCPP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalMonoCPPColumn",
        "minWidth": 120,
        "group": "tcoTotalColumns"
      },
      "totalColorCPP": {
        "name": "totalColorCPP",
        "field": "totalColorCPP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalColorCPPColumn",
        "minWidth": 120,
        "group": "tcoTotalColumns"
      },
      "totalCPP": {
        "name": "totalCPP",
        "field": "totalCPP",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "totalCPPColumn",
        "minWidth": 120,
        "group": "tcoTotalColumns"
      },
      "mvSupply": {
        "name": "mvSupply",
        "field": "mvSupply",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/mvSupplyCell.html",
        "headerCellClass": "mvSupplyColumn",
        "minWidth": 120
      },
      "mvSupplyCostStatus": {
        "name": "mvSupplyCostStatus",
        "field": "mvSupplyCostStatus",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/mvSupplyCostingCell.html",
        "headerCellClass": "mvSupplyCostStatusColumn",
        "minWidth": 120
      },
      "mvService": {
        "name": "mvService",
        "field": "mvService",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/mvServiceCell.html",
        "headerCellClass": "mvServiceColumn",
        "minWidth": 120
      },
      "mvServiceCostStatus": {
        "name": "mvServiceCostStatus",
        "field": "mvServiceCostStatus",
        "width": 120,
        "enableSorting": false,
        "cellTooltip": true,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/mvServiceCostingCell.html",
        "headerCellClass": "mvServiceCostStatusColumn",
        "minWidth": 120
      },
      "mvDartZone": {
        "name": "mvDartZone",
        "field": "mvDartZone",
        "cellTooltip": true,
        "width": 120,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/mvZoneCell.html",
        "headerCellClass": "mvDartZoneColumn",
        "minWidth": 120
      },
      "macAddress": {
        "name": "macAddress",
        "field": "macAddress",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "macAddressColumn",
        "type": "string",
        "minWidth": 120
      },
      "hostName": {
        "name": "hostName",
        "field": "hostName",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "hostNameColumn",
        "type": "string",
        "minWidth": 120
      },
      "subnetMask": {
        "name": "subnetMask",
        "field": "subnetMask",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "subnetMaskColumn",
        "type": "string",
        "minWidth": 120
      },
      "iPAddress": {
        "name": "iPAddress",
        "field": "iPAddress",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "iPAddressColumn",
        "type": "string",
        "minWidth": 120
      },
      "gateway": {
        "name": "gateway",
        "field": "gateway",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "gatewayColumn",
        "type": "string",
        "minWidth": 120
      },
      "dateIntroduced": {
        "name": "dateIntroduced",
        "field": "dateIntroduced",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "dateIntroducedColumn",
        "type": "string",
        "minWidth": 120
      },
      "dateManufactured": {
        "name": "dateManufactured",
        "field": "dateManufactured",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "dateManufacturedColumn",
        "type": "string",
        "minWidth": 120
      },
      "dateInstalled": {
        "name": "dateInstalled",
        "field": "dateInstalled",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "dateInstalledColumn",
        "type": "string",
        "minWidth": 120
      },
      "serviceID": {
        "name": "serviceID",
        "field": "serviceID",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "serviceIDColumn",
        "type": "string",
        "minWidth": 120
      },
      "location": {
        "name": "location",
        "field": "location",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "locationColumn",
        "type": "string",
        "minWidth": 120
      },
      "placement": {
        "name": "placement",
        "field": "placement",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "placementColumn",
        "minWidth": 120
      },
      "connectionType": {
        "name": "connectionType",
        "field": "connectionType",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "connectionTypeColumn",
        "minWidth": 120
      },
      "printQueue": {
        "name": "printQueue",
        "field": "printQueue",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "printQueueColumn",
        "minWidth": 120
      },
      "faxNumber": {
        "name": "faxNumber",
        "field": "faxNumber",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "faxNumberColumn",
        "minWidth": 120
      },
      "dartUploadStrategy": {
        "name": "dartUploadStrategy",
        "field": "dartUploadStrategy",
        "cellTooltip": true,
        "width": 180,
        "enablePinning": false,
        "cellTemplate": "vendor/hp-porticosd/ngPorticoSD/views/templates/dartDealUploadCell.html",
        "headerCellClass": "dartUploadStrategyColumn",
        "minWidth": 120
      },
      "custom1": {
        "name": "custom1",
        "field": "custom1",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "connectionTypeColumn",
        "minWidth": 120
      },
      "custom2": {
        "name": "custom2",
        "field": "custom2",
        "width": "120",
        "enableSorting": true,
        "cellTooltip": true,
        "enablePinning": false,
        "headerCellClass": "connectionTypeColumn",
        "minWidth": 120
      }
    },
    obj2 = {
      "custom3": {
        "name": "custom3",
        "field": "custom3",
        "width": 250,
        "pinnedLeft": true,
        "enableColumnMoving": false,
        "enableHiding": false,
        "enableSorting": false,
        "enableColumnMenu": false,
        "enableFiltering": false,
        "headerCellClass": "levelColumn"
      },
      "custom4": {
        "name": "custom4",
        "field": "custom4",
        "width": 250,
        "pinnedLeft": true,
        "enableColumnMoving": false,
        "enableHiding": false,
        "enableSorting": false,
        "enableColumnMenu": false,
        "enableFiltering": false,
        "headerCellClass": "levelColumn"
      }
    };
var obj3 = objectMerge(obj1, obj2);
console.log(obj3);
