"use strict";
module.exports = {
    up: (queryInterface, Sequelize) => {
        return Promise.all([
            queryInterface.addColumn(
                "employee_verification",
                "id_manual_review",
                Sequelize.BOOLEAN
            ),
            queryInterface.addColumn(
                "payment",
                "couponCode",
                Sequelize.STRING(500)
            ),
            queryInterface.addColumn(
                "employement",
                "consent",
                Sequelize.BOOLEAN
            ),
            queryInterface.addColumn(
                "employement",
                "super_admin_status",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "education",
                "super_admin_status",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "professional_license",
                "super_admin_status",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employee_verification",
                "super_admin_status",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employee_verification",
                "criminal_verified",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employee_verification",
                "criminal_verified",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employee_verification",
                "criminal_verified",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "user_profile",
                "email_sent_time",
                Sequelize.BIGINT
            ),
            queryInterface.addColumn("employee", "status", {
                type: Sequelize.ENUM,
                values: ['VERIFIED', 'PENDING', 'ENTERED', 'FAILED'],
                allowNull: true
            }),
            queryInterface.addColumn(
                "education",
                "status",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "professional_license",
                "status",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employement",
                "status",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employee",
                "email_sent",
                Sequelize.BOOLEAN
            ),
            queryInterface.addColumn(
                "company",
                "s3_logo",
                Sequelize.STRING(255)
            ),
            queryInterface.addColumn(
                "company",
                "employement_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "company",
                "education_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "company",
                "license_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "company",
                "civilcourt_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "company",
                "dl_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "pricing",
                "package",
                Sequelize.STRING(128)
            ),
            queryInterface.addColumn(
                "pricing",
                "CIVILCOURT",
                Sequelize.BIGINT
            ),
            queryInterface.addColumn(
                "employee",
                "employement_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "employee",
                "education_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "employee",
                "license_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "employee",
                "civilcourt_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "employee",
                "dl_limit",
                Sequelize.INTEGER
            ),
            queryInterface.addColumn(
                "employee",
                "background_check_request",
                Sequelize.BOOLEAN
            ),
            queryInterface.addColumn(
                "employee",
                "s3_passport_verified",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employee",
                "s3_dl_verified",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn("company", "credits", {
                type: Sequelize.BIGINT,
                defaultValue: 0
            }),
            queryInterface.addColumn(
                "employement",
                "job_type",
                Sequelize.STRING(500)
            ),
            queryInterface.addColumn(
                "employement",
                "reason_for_leaving",
                Sequelize.STRING(500)
            ),
            queryInterface.addColumn(
                "user_profile",
                "stripe_id",
                Sequelize.STRING(256)
            ),
            queryInterface.addColumn("employee", "package", Sequelize.STRING(64)),
            queryInterface.addColumn(
                "employee",
                "s3_gov_id_match",
                Sequelize.TINYINT(1)
            ),
            queryInterface.addColumn(
                "employee",
                "verification_type",
                Sequelize.STRING(64)
            )
        ]);
    },
    down: (queryInterface, Sequelize) => {
        return queryInterface.removeColumn("employee", "s3_passport_verified");
    }
};