function remove(pool, ids) {
  if (arguments.length === 2) {
    if (true) {
      ids.forEach(function (id) {
        var rowNumber = pool.findIndex(function (element) {
          return element.id === id;
        });
        if (rowNumber >= 0) {
          pool.splice(rowNumber, 1);
        }
      });
    }
  }
  else if (pool && pool.length > 0) {
    pool.splice(0, pool.length);
  }
}

function removeLicense(tabularPool, level) {
  let licenseId, licenses, licenseParentIds, licenseParents;
  if(level.type === 'SOFTWARE_LICENSE') {
    licenseId = level.solutionId + "-" + level.productName + "-" + level.sku
    PorticoSDPoolManager.remove(tabularPool, [licenseId]);
    licenses = tabularPool.filter(function (row) {
      return row.value.levelId === level.solutionId && row.value.type === PorticoSDConfiguration.LEVEL_SOFTWARE_LICENSE;
    });
    if (!licenses.length) {
      licenseParents = tabularPool.filter(function (row) {
        return row.value.levelId === level.solutionId;
      });
    }
  } else if (level.type === 'COUNTRY') {
    licenseParents = tabularPool.filter(function (row) {
      return row.value.countryId === level._id && (row.value.type === "SOFTWARE_SOLN" || row.value.type === "SOFTWARE_PRODUCT" || row.value.type === "SOFTWARE_LICENSE");
    });
    licenseParentIds = licenseParents.map(function (value) {
      return value.id;
    });
    remove(tabularPool, licenseParentIds);
  }
  licenseParentIds = licenseParents.map(function (value) {
    return value.id;
  });
  PorticoSDPoolManager.remove(tabularPool, licenseParentIds);
}

function updateQty(tabularPool, level) {
try {
  let licenseId, licenses, licenseParentIds, licenseParents;
  licenseId = (level.solutionId + "-" + level.productName + "-" + level.sku) || "";
  if (level.type === 'SOFTWARE_LICENSE') {
    licenses = tabularPool.filter(function (row) {
      return row.id === licenseId;
    });
    licenses[0].value.quantity = level.quantity;
    console.log(licenses[0].value.quantity);
  } else if (level.type === 'COUNTRY') {
    licenseParents = tabularPool.filter(function (row) {
      return row.value.countryId === level._id && (row.value.type === "SOFTWARE_SOLN" || row.value.type === "SOFTWARE_PRODUCT" || row.value.type === "SOFTWARE_LICENSE");
    });
    licenseParentIds = licenseParents.map(function (value) {
      return value.id;
    });
    remove(tabularPool, licenseParentIds);
  }
  if (licenseParents && licenseParents.length) {
    licenseParentIds = licenseParents.map(function (value) {
      return value.id;
    });
    PorticoSDPoolManager.remove(tabularPool, licenseParentIds);
  }

 } catch (e) {
  console.error("some error has occured", e);
}
}


















let data = [
  {
    "id": "5da56f2372a7cd37332ce57b",
    "value": {
      "level": "q2qq",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 0,
      "levelId": "5da56f2372a7cd37332ce57b",
      "isRealAsset": "",
      "type": "project",
      "outcome": "",
      "monoCPPUsd": "",
      "totalRevenueUsd": "",
      "totalCPPUsd": "",
      "colorCPPUsd": "",
      "baseFeeUsd": "",
      "monoClickUsd": "",
      "colorClickUsd": "",
      "bestColorClickUsd": "",
      "netPriceUsd": "",
      "upfrontChargeUsd": "",
      "monoCPPLc": "",
      "totalRevenueLc": "",
      "totalCPPLc": "",
      "colorCPPLc": "",
      "baseFeeLc": "",
      "monoClickLc": "",
      "colorClickLc": "",
      "bestColorClickLc": "",
      "netPriceLc": "",
      "upfrontChargeLc": "",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "",
      "siteId": "",
      "buildingId": "",
      "floorId": "",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartUploadStrategy": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-0037"
    }
  },
  {
    "id": "5da56f2372a7cd37332ce57c",
    "value": {
      "level": "United States",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 1,
      "levelId": "5da56f2372a7cd37332ce57c",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "",
      "totalRevenueUsd": "",
      "totalCPPUsd": "",
      "colorCPPUsd": "",
      "baseFeeUsd": "",
      "monoClickUsd": "",
      "colorClickUsd": "",
      "bestColorClickUsd": "",
      "netPriceUsd": "",
      "upfrontChargeUsd": "",
      "monoCPPLc": "",
      "totalRevenueLc": "",
      "totalCPPLc": "",
      "colorCPPLc": "",
      "baseFeeLc": "",
      "monoClickLc": "",
      "colorClickLc": "",
      "bestColorClickLc": "",
      "netPriceLc": "",
      "upfrontChargeLc": "",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f2372a7cd37332ce57c",
      "siteId": "",
      "buildingId": "",
      "floorId": "",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-0039"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58a",
    "value": {
      "_id": "5da56f4872a7cd37332ce58a",
      "name": "Genius_Bytes",
      "countryId": "5da56f2372a7cd37332ce57c",
      "projectId": "5da56f2372a7cd37332ce57b",
      "products": [
        {
          "name": "*Genius_Bytes",
          "billingModel": "Base + Click No Minimum",
          "hardwarePurchase": "Embedded Lease",
          "licenses": [
            {
              "sku": "GNUASF3E",
              "description": "Genius Bytes Accounting SFP 3 yr e-LTU",
              "quantity": "10"
            },
            {
              "sku": "GNUASF5E",
              "description": "Genius Bytes Accounting SFP 5 yr e-LTU",
              "quantity": "10"
            },
            {
              "sku": "GNUCR11E",
              "description": "Genius Bytes OCR Client 1y E-LTU",
              "quantity": "10"
            },
            {
              "sku": "GNUASF6E",
              "description": "Genius Bytes Accounting SFP 3 yr e-LTU",
              "quantity": "10"
            }
          ]
        }
      ],
      "$$treeLevel": 2,
      "level": "Genius_Bytes",
      "type": "SOFTWARE_SOLN",
      "levelId": "5da56f4872a7cd37332ce58a",
      "$$hashKey": "uiGrid-003B"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58a-*Genius_Bytes",
    "value": {
      "name": "*Genius_Bytes",
      "billingModel": "Base + Click No Minimum",
      "hardwarePurchase": "Embedded Lease",
      "$$treeLevel": 3,
      "level": "*Genius_Bytes",
      "type": "SOFTWARE_PRODUCT",
      "levelId": "5da56f4872a7cd37332ce58a",
      "countryId": "5da56f2372a7cd37332ce57c",
      "hwDisposition": "Embedded Lease",
      "$$hashKey": "uiGrid-003D"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58a-*Genius_Bytes-GNUASF3E",
    "value": {
      "sku": "GNUASF3E",
      "description": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "quantity": "10",
      "$$treeLevel": 5,
      "level": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "deviceQty": "10",
      "type": "SOFTWARE_LICENSE",
      "levelId": "5da56f4872a7cd37332ce58a",
      "countryId": "5da56f2372a7cd37332ce57c",
      "productName": "*Genius_Bytes",
      "$$hashKey": "uiGrid-003F"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58a-*Genius_Bytes-GNUASF5E",
    "value": {
      "sku": "GNUASF5E",
      "description": "Genius Bytes Accounting SFP 5 yr e-LTU",
      "quantity": "10",
      "$$treeLevel": 5,
      "level": "Genius Bytes Accounting SFP 5 yr e-LTU",
      "deviceQty": "10",
      "type": "SOFTWARE_LICENSE",
      "levelId": "5da56f4872a7cd37332ce58a",
      "countryId": "5da56f2372a7cd37332ce57c",
      "productName": "*Genius_Bytes",
      "$$hashKey": "uiGrid-003H"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58a-*Genius_Bytes-GNUCR11E",
    "value": {
      "sku": "GNUCR11E",
      "description": "Genius Bytes OCR Client 1y E-LTU",
      "quantity": "10",
      "$$treeLevel": 5,
      "level": "Genius Bytes OCR Client 1y E-LTU",
      "deviceQty": "10",
      "type": "SOFTWARE_LICENSE",
      "levelId": "5da56f4872a7cd37332ce58a",
      "countryId": "5da56f2372a7cd37332ce57c",
      "productName": "*Genius_Bytes",
      "$$hashKey": "uiGrid-003J"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58a-*Genius_Bytes-GNUASF6E",
    "value": {
      "sku": "GNUASF6E",
      "description": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "quantity": "10",
      "$$treeLevel": 5,
      "level": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "deviceQty": "10",
      "type": "SOFTWARE_LICENSE",
      "levelId": "5da56f4872a7cd37332ce58a",
      "countryId": "5da56f2372a7cd37332ce57c",
      "productName": "*Genius_Bytes",
      "$$hashKey": "uiGrid-003L"
    }
  },
  {
    "id": "5da56f2372a7cd37332ce57d",
    "value": {
      "level": "Site 1",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 2,
      "levelId": "5da56f2372a7cd37332ce57d",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "0.00000",
      "totalRevenueUsd": "",
      "totalCPPUsd": "0.00000",
      "colorCPPUsd": "0.00000",
      "baseFeeUsd": "0.00",
      "monoClickUsd": "0.00000",
      "colorClickUsd": "0.00000",
      "bestColorClickUsd": "0.00000",
      "netPriceUsd": "0.00000",
      "upfrontChargeUsd": "0.00",
      "monoCPPLc": "0.00000",
      "totalRevenueLc": "",
      "totalCPPLc": "0.00000",
      "colorCPPLc": "0.00000",
      "baseFeeLc": "0.00",
      "monoClickLc": "0.00000",
      "colorClickLc": "0.00000",
      "bestColorClickLc": "0.00000",
      "netPriceLc": "0.00000",
      "upfrontChargeLc": "0.00",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f2372a7cd37332ce57c",
      "siteId": "5da56f2372a7cd37332ce57d",
      "buildingId": "",
      "floorId": "",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-003N"
    }
  },
  {
    "id": "5da56f2372a7cd37332ce57e",
    "value": {
      "level": "Building 1",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 3,
      "levelId": "5da56f2372a7cd37332ce57e",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "0.00000",
      "totalRevenueUsd": "",
      "totalCPPUsd": "0.00000",
      "colorCPPUsd": "0.00000",
      "baseFeeUsd": "0.00",
      "monoClickUsd": "0.00000",
      "colorClickUsd": "0.00000",
      "bestColorClickUsd": "0.00000",
      "netPriceUsd": "0.00000",
      "upfrontChargeUsd": "0.00",
      "monoCPPLc": "0.00000",
      "totalRevenueLc": "",
      "totalCPPLc": "0.00000",
      "colorCPPLc": "0.00000",
      "baseFeeLc": "0.00",
      "monoClickLc": "0.00000",
      "colorClickLc": "0.00000",
      "bestColorClickLc": "0.00000",
      "netPriceLc": "0.00000",
      "upfrontChargeLc": "0.00",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f2372a7cd37332ce57c",
      "siteId": "5da56f2372a7cd37332ce57d",
      "buildingId": "5da56f2372a7cd37332ce57e",
      "floorId": "",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-003P"
    }
  },
  {
    "id": "5da56f2372a7cd37332ce57f",
    "value": {
      "level": "Floor 0",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 4,
      "levelId": "5da56f2372a7cd37332ce57f",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "0.00000",
      "totalRevenueUsd": "",
      "totalCPPUsd": "0.00000",
      "colorCPPUsd": "0.00000",
      "baseFeeUsd": "0.00",
      "monoClickUsd": "0.00000",
      "colorClickUsd": "0.00000",
      "bestColorClickUsd": "0.00000",
      "netPriceUsd": "0.00000",
      "upfrontChargeUsd": "0.00",
      "monoCPPLc": "0.00000",
      "totalRevenueLc": "",
      "totalCPPLc": "0.00000",
      "colorCPPLc": "0.00000",
      "baseFeeLc": "0.00",
      "monoClickLc": "0.00000",
      "colorClickLc": "0.00000",
      "bestColorClickLc": "0.00000",
      "netPriceLc": "0.00000",
      "upfrontChargeLc": "0.00",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f2372a7cd37332ce57c",
      "siteId": "5da56f2372a7cd37332ce57d",
      "buildingId": "5da56f2372a7cd37332ce57e",
      "floorId": "5da56f2372a7cd37332ce57f",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-003R"
    }
  },
  {
    "id": "5da56f4781872e573d6b0b43",
    "value": {
      "level": "India",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 1,
      "levelId": "5da56f4781872e573d6b0b43",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "",
      "totalRevenueUsd": "",
      "totalCPPUsd": "",
      "colorCPPUsd": "",
      "baseFeeUsd": "",
      "monoClickUsd": "",
      "colorClickUsd": "",
      "bestColorClickUsd": "",
      "netPriceUsd": "",
      "upfrontChargeUsd": "",
      "monoCPPLc": "",
      "totalRevenueLc": "",
      "totalCPPLc": "",
      "colorCPPLc": "",
      "baseFeeLc": "",
      "monoClickLc": "",
      "colorClickLc": "",
      "bestColorClickLc": "",
      "netPriceLc": "",
      "upfrontChargeLc": "",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f4781872e573d6b0b43",
      "siteId": "",
      "buildingId": "",
      "floorId": "",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-003T"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58b",
    "value": {
      "_id": "5da56f4872a7cd37332ce58b",
      "name": "Genius_Bytes",
      "countryId": "5da56f4781872e573d6b0b43",
      "projectId": "5da56f2372a7cd37332ce57b",
      "products": [
        {
          "name": "*Genius_Bytes",
          "billingModel": "Base + Click No Minimum",
          "hardwarePurchase": "Embedded Lease",
          "licenses": [
            {
              "sku": "GNUASF7E",
              "description": "Genius Bytes Accounting SFP 3 yr e-LTU",
              "quantity": "10"
            }
          ]
        }
      ],
      "$$treeLevel": 2,
      "level": "Genius_Bytes",
      "type": "SOFTWARE_SOLN",
      "levelId": "5da56f4872a7cd37332ce58b",
      "$$hashKey": "uiGrid-003V"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58b-*Genius_Bytes",
    "value": {
      "name": "*Genius_Bytes",
      "billingModel": "Base + Click No Minimum",
      "hardwarePurchase": "Embedded Lease",
      "$$treeLevel": 3,
      "level": "*Genius_Bytes",
      "type": "SOFTWARE_PRODUCT",
      "levelId": "5da56f4872a7cd37332ce58b",
      "countryId": "5da56f4781872e573d6b0b43",
      "hwDisposition": "Embedded Lease",
      "$$hashKey": "uiGrid-003X"
    }
  },
  {
    "id": "5da56f4872a7cd37332ce58b-*Genius_Bytes-GNUASF7E",
    "value": {
      "sku": "GNUASF7E",
      "description": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "quantity": "10",
      "$$treeLevel": 5,
      "level": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "deviceQty": "10",
      "type": "SOFTWARE_LICENSE",
      "levelId": "5da56f4872a7cd37332ce58b",
      "countryId": "5da56f4781872e573d6b0b43",
      "productName": "*Genius_Bytes",
      "$$hashKey": "uiGrid-003Z"
    }
  },
  {
    "id": "5da56f4781872e573d6b0b44",
    "value": {
      "level": "Site 1",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 2,
      "levelId": "5da56f4781872e573d6b0b44",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "0.00000",
      "totalRevenueUsd": "",
      "totalCPPUsd": "0.00000",
      "colorCPPUsd": "0.00000",
      "baseFeeUsd": "0.00",
      "monoClickUsd": "0.00000",
      "colorClickUsd": "0.00000",
      "bestColorClickUsd": "0.00000",
      "netPriceUsd": "0.00000",
      "upfrontChargeUsd": "0.00",
      "monoCPPLc": "0.00000",
      "totalRevenueLc": "",
      "totalCPPLc": "0.00000",
      "colorCPPLc": "0.00000",
      "baseFeeLc": "0.00",
      "monoClickLc": "0.00000",
      "colorClickLc": "0.00000",
      "bestColorClickLc": "0.00000",
      "netPriceLc": "0.00000",
      "upfrontChargeLc": "0.00",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f4781872e573d6b0b43",
      "siteId": "5da56f4781872e573d6b0b44",
      "buildingId": "",
      "floorId": "",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-0041"
    }
  },
  {
    "id": "5da56f4781872e573d6b0b45",
    "value": {
      "level": "Building 1",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 3,
      "levelId": "5da56f4781872e573d6b0b45",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "0.00000",
      "totalRevenueUsd": "",
      "totalCPPUsd": "0.00000",
      "colorCPPUsd": "0.00000",
      "baseFeeUsd": "0.00",
      "monoClickUsd": "0.00000",
      "colorClickUsd": "0.00000",
      "bestColorClickUsd": "0.00000",
      "netPriceUsd": "0.00000",
      "upfrontChargeUsd": "0.00",
      "monoCPPLc": "0.00000",
      "totalRevenueLc": "",
      "totalCPPLc": "0.00000",
      "colorCPPLc": "0.00000",
      "baseFeeLc": "0.00",
      "monoClickLc": "0.00000",
      "colorClickLc": "0.00000",
      "bestColorClickLc": "0.00000",
      "netPriceLc": "0.00000",
      "upfrontChargeLc": "0.00",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f4781872e573d6b0b43",
      "siteId": "5da56f4781872e573d6b0b44",
      "buildingId": "5da56f4781872e573d6b0b45",
      "floorId": "",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-0043"
    }
  },
  {
    "id": "5da56f4781872e573d6b0b46",
    "value": {
      "level": "Floor 0",
      "selection": false,
      "subEnvID": "",
      "mapId": "",
      "deviceModel": "",
      "pageSize": "",
      "deviceType": "",
      "deviceQty": "",
      "hwDisposition": "",
      "mvService": "",
      "mvServiceCostStatus": "",
      "mvSupply": "",
      "mvSupplyCostStatus": "",
      "mvDartZone": "",
      "sku": "",
      "productId": "",
      "pvtInA3": "",
      "pvtIn": "",
      "pvtOutA3": "",
      "pvtOut": "",
      "ampv": "",
      "monoPages": "",
      "colorPages": "",
      "monthlyMonoPages": "",
      "monthlyColorPages": "",
      "monthlyColorProfPages": "",
      "monthlyPages": "",
      "colorTotalPagesPercentage": "",
      "a3Percentage": "",
      "colorA3Percentage": "",
      "monoA3Percentage": "",
      "age": "",
      "lifeTimeEngineLife": "",
      "currentLifeTimeEngineLife": "",
      "proposedLifeTimeEngineLife": "",
      "eoslPast": "",
      "currentEoslPast": "",
      "proposedEoslPast": "",
      "assetId": "",
      "accessoryId": "",
      "$$treeLevel": 4,
      "levelId": "5da56f4781872e573d6b0b46",
      "isRealAsset": true,
      "type": "level",
      "outcome": "",
      "monoCPPUsd": "0.00000",
      "totalRevenueUsd": "",
      "totalCPPUsd": "0.00000",
      "colorCPPUsd": "0.00000",
      "baseFeeUsd": "0.00",
      "monoClickUsd": "0.00000",
      "colorClickUsd": "0.00000",
      "bestColorClickUsd": "0.00000",
      "netPriceUsd": "0.00000",
      "upfrontChargeUsd": "0.00",
      "monoCPPLc": "0.00000",
      "totalRevenueLc": "",
      "totalCPPLc": "0.00000",
      "colorCPPLc": "0.00000",
      "baseFeeLc": "0.00",
      "monoClickLc": "0.00000",
      "colorClickLc": "0.00000",
      "bestColorClickLc": "0.00000",
      "netPriceLc": "0.00000",
      "upfrontChargeLc": "0.00",
      "proposedMonthlyPageVolumeMono": "",
      "proposedMonthlyPageVolumeColor": "",
      "proposedAmpv": "",
      "proposedColorTotalPagesPercentage": "",
      "initHwDispositions": {},
      "initService": [],
      "initSupply": [],
      "initMvDartZone": [],
      "countryId": "5da56f4781872e573d6b0b43",
      "siteId": "5da56f4781872e573d6b0b44",
      "buildingId": "5da56f4781872e573d6b0b45",
      "floorId": "5da56f4781872e573d6b0b46",
      "department": "",
      "floor": "",
      "colorPro": "",
      "colorProTotalPagesPercentage": "",
      "proposedColorProMonthlyVolume": "",
      "proposedColorProTotalPagesPercentage": "",
      "totalCppToner": "",
      "monoCppToner": "",
      "colorCppToner": "",
      "totalTcoToner": "",
      "monoTcoToner": "",
      "colorTcoToner": "",
      "laborRateRP": "",
      "laborTravelHoursRP": "",
      "laborRepairHoursRP": "",
      "totalCppRP": "",
      "monoCppRP": "",
      "colorCppRP": "",
      "totalTcoRP": "",
      "monoTcoRP": "",
      "colorTcoRP": "",
      "avgPwcService": "",
      "totalCppService": "",
      "monoCppService": "",
      "colorCppService": "",
      "totalTcoService": "",
      "monoTcoService": "",
      "colorTcoService": "",
      "avgPowPricePower": "",
      "workHoursPerDayPower": "",
      "workDaysPerWeekPower": "",
      "weeksPerYearPower": "",
      "isOnNightAndWeekends": "",
      "powerRateActive": "",
      "powerRateIdle": "",
      "powerRateSave": "",
      "totalCppPower": "",
      "monoCppPower": "",
      "colorCppPower": "",
      "totalTcoPower": "",
      "monoTcoPower": "",
      "colorTcoPower": "",
      "paperCostPerSheetPaper": "",
      "duplexPercentagePaper": "",
      "isDuplexCapablePaper": "",
      "totalCppPaper": "",
      "monoCppPaper": "",
      "colorCppPaper": "",
      "totalTcoPaper": "",
      "monoTcoPaper": "",
      "colorTcoPaper": "",
      "deviceCostHardware": "",
      "totalCppHardware": "",
      "monoCppHardware": "",
      "colorCppHardware": "",
      "totalTcoHardware": "",
      "monoTcoHardware": "",
      "colorTcoHardware": "",
      "totalEnergyInKWH": "",
      "co2PaperKG": "",
      "energyCO2KG": "",
      "energyCO2KGbyGeography": "",
      "noOfTreesCutDown": "",
      "literOfOilRequired": "",
      "totalAssetManagementCost": "",
      "supplyProcessTotalManHrsCostsPerYr": "",
      "totalDeviceSpaceCostperYr": "",
      "helpDeskCostperPrinterBasedonNumberofPrinters": "",
      "helpDeskCostperPrinterBasedonNumberofUsers": "",
      "totalPurchasingCostofDeviceperYr": "",
      "totalITMgmtCostofDevicePerYr": "",
      "totalMonoCPP": "",
      "totalColorCPP": "",
      "totalCPP": "",
      "macAddress": "",
      "hostName": "",
      "subnetMask": "",
      "gateway": "",
      "dateIntroduced": "",
      "dateManufactured": "",
      "dateInstalled": "",
      "serviceID": "",
      "location": "",
      "placement": "",
      "connectionType": "",
      "printQueue": "",
      "faxNumber": "",
      "iPAddress": "",
      "serialNumber": "",
      "dartDealKey": "",
      "dartWorkflowState": "",
      "dartCheckoutUser": "",
      "isEligibleForTcoRemap": false,
      "isAssetProxy": false,
      "isMultiVendorAsset": false,
      "assetAbbreviation": "",
      "accessories": "",
      "reducedProposedPageVolume": "",
      "$$hashKey": "uiGrid-0045"
    }
  }
];
let resp = updateQty(data,
    {
      "sku": "GNUASF7E",
      "description": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "quantity": "10000",
      "solutionId":"5da56f4872a7cd37332ce58b",
      "$$treeLevel": 5,
      "level": "Genius Bytes Accounting SFP 3 yr e-LTU",
      "deviceQty": "100000000000",
      "type": "SOFTWARE_LICENSE",
      "levelId": "5da56f4872a7cd37332ce58b",
      "countryId": "5da56f4781872e573d6b0b43",
      "productName": "*Genius_Bytes",
      "$$hashKey": "uiGrid-003Z"
    }
);
// console.log(resp);
